# Generated by Django 5.0.1 on 2024-01-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_stockdata_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
