# Generated by Django 5.0.1 on 2024-01-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_stockdata_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
