version: '3.8'

services:
  celery:
    container_name: celery_con
    image: celery_image
    build: .
    command: celery -A stockmarket worker --loglevel=info
    depends_on:
      - redis
      - db
      - app
  flower:
    container_name: flower_con
    image: flower_image
    build: .
    command: celery -A stockmarket flower
    depends_on:
      - redis
      - app
      - celery
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/stock_data
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=stock_database
      - DJANGO_DB_USER=user1
      - DJANGO_DB_PASSWORD=password
      - DJANGO_REDIS_HOST=redis
      - DJANGO_REDIS_PORT=6379
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: stock_database
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password
  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"